### ISSUE TITLE
GCP Launch

### ISSUE THREAD

**Issue by asmahood** [uwpokerclub/tickets#101]
**Please describe the feature**

**Checklist**

APP - https://github.com/uwpokerclub/app
API - https://github.com/uwpokerclub/api

- [x] #102
- [x] #103
- [x] #104
- [x] #105
- [x] #106
- [x] Test charts locally @asmahood 
- [x] Create GKE cluster
- [x] Deploy charts to GKE cluster @uwpokerclub/devops 
- [x] Purchase CloudSQL for PostgreSQL @uwpokerclub/devops 
- [x] Configure APP/API to use CloudSQL@uwpokerclub/devops 
- [x] Test APP/API @uwpokerclub/devops 

To be completed whenever:
- [x] Purchase domain
- [x] Figure out SSL certs with LetsEncrypt
