### ISSUE TITLE
Authentication Overhaul

### ISSUE THREAD

**Issue by asmahood** [uwpokerclub/tickets#211]
## Description
Currently, the website does not have any sort of session management. "Sessions" are currently handled using JWTs, which means that sessions are nearly impossible to invalidate. In order to support an upcoming feature (#209), the website will need to be able to support multiple active logins at once. Which also means that the need for proper session management is critical.

This feature proposes the introduction of sessions and session management on the API. To make this as backwards compatible as possible, this should be implemented on a new route and the existing routes should remain in place until the app has been updated and is working with the new system.

## MVP
- All login attempts will generate sessions that will be managed by the API server and database
- To keep backwards compatibility, a new route should be created to create new sessions
- All authentication protected routes should look for valid sessions instead of using the JWT
- A new route should be created to terminate sessions (logout)
  - This route should only be available to active sessions 
- The web app should be updated to handle login/logouts from these new routes
- Old JWT logic should be removed

## Design
[Click this link to view the full Miro board](https://miro.com/app/board/uXjVKNrrRBw=/)
- [Brainstorming](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587783544340&cot=14)
- [API Changes](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587787760061&cot=14)
- [ER Diagram](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587786262738&cot=14)
- [Schema Changes](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587885323275&cot=14)
- [Sequence diagrams](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587659538684&cot=14)
  - [Creating a new session](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587887202356&cot=10)
  - [Authenticating a protected route](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587887202702&cot=10)
  - [Invalidating a session](https://miro.com/app/board/uXjVKNrrRBw=/?moveToWidget=3458764587887202848&cot=10)

## Milestones
- [x] Database updated
  - [x] uwpokerclub/api#272
- [x] API supports session based login
  - [x] uwpokerclub/api#273
  - [x] uwpokerclub/api#274
  - [x] uwpokerclub/api#275
  - [x] uwpokerclub/api#279
- [x] Webapp updated to support session based login/logout
  - [x] uwpokerclub/app#730
  - [x] uwpokerclub/app#731
- [x] Old JWT logic removed
  - [x] uwpokerclub/api#296
